/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.PhoneAcsImp;
import com.model.Phone;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MobileView extends javax.swing.JFrame {

    /**
     * Creates new form MobileView
     */
    public MobileView() {
        initComponents();
        Load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pno_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pname_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brand_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        category_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        exit_btn = new javax.swing.JButton();
        search_btn2 = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        manage_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIGITAL TECH MOBILE SHOP");
        setBackground(new java.awt.Color(255, 102, 255));

        jPanel1.setBackground(new java.awt.Color(4, 59, 92));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Cooper Std Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 246, 244));
        jLabel1.setText("DIGITAL TECH MOBILE SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        jTable1.setBackground(new java.awt.Color(255, 246, 244));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone ID", "Phone Name", "Brand", "Category", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(4, 59, 92));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone ID");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone Name");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");

        exit_btn.setBackground(new java.awt.Color(186, 216, 238));
        exit_btn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        search_btn2.setBackground(new java.awt.Color(186, 216, 238));
        search_btn2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        search_btn2.setText("SEARCH BY BRAND");
        search_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn2ActionPerformed(evt);
            }
        });

        search_btn.setBackground(new java.awt.Color(186, 216, 238));
        search_btn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        search_btn.setText("SEARCH BY NAME");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(186, 216, 238));
        delete_btn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setBackground(new java.awt.Color(186, 216, 238));
        update_btn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(186, 216, 238));
        add_btn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        add_btn.setText("ADD");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        manage_btn.setBackground(new java.awt.Color(255, 0, 0));
        manage_btn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        manage_btn.setForeground(new java.awt.Color(255, 255, 255));
        manage_btn.setText("MANAGE USERS");
        manage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brand_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(manage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(pname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(brand_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(category_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add_btn)
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn)
                        .addGap(18, 18, 18)
                        .addComponent(search_btn)
                        .addGap(18, 18, 18)
                        .addComponent(search_btn2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manage_btn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void Load(){  //creating a method 
        
         PhoneAcsImp acs = new PhoneAcsImp(); //creating an object in phoneAcsImp class
        List<Phone> list = acs.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel(); //object for jtable1
        DFT.setRowCount(0); 
        for(Phone p: list) //creating simple for loop
        {
            int pno = p.getPno();                       //getting values through getter methods
            String pname = p.getPname();                //getting values through getter methods
            String brand = p.getBrand();                //getting values through getter methods
            String category = p.getCategory();          //getting values through getter methods
            int price = p.getPrice();                   //getting values through getter methods
            DFT.addRow(new Object[]{pno,pname,brand,category,price});
        }    
        
    } 
    
    
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        
        //creating instance of phone class
        Phone p = new Phone();       //creating an object as p in phone class/ p is a new phone in phone class
        int pno = Integer.parseInt(pno_txt.getText());
        String name = pname_txt.getText();
        String brand = brand_txt.getText();
        String category = category_txt.getText();
        int price = Integer.parseInt(price_txt.getText());
        
        p.setPno(pno);            //setting values through setter methods
        p.setPname(name);         //setting values through setter methods
        p.setBrand(brand);        //setting values through setter methods
        p.setCategory(category);  //setting values through setter methods
        p.setPrice(price);        //setting values through setter methods
        
        //creating instance of PhoneAcsImp class
        PhoneAcsImp acs = new PhoneAcsImp();
        acs.add(p); //using the add method of PhoneAscImp class
        Load();     //calling load method 
        pno_txt.setText("");            //setting values through setter methods
        pname_txt.setText("");          //setting values through setter methods
        brand_txt.setText("");          //setting values through setter methods
        category_txt.setText("");       //setting values through setter methods
        price_txt.setText("");          //setting values through setter methods
        pname_txt.requestFocus();       //requesting new data
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        
        Phone p = new Phone();  //creating an object for the Phone class
        int pno = Integer.parseInt(pno_txt.getText()); //creating variable for the pno & getting values through getter methods
        String brand = brand_txt .getText();            //creating variable for the brand & getting values through getter methods
        String category = category_txt.getText();       //creating variable for the category & getting values through getter methods
        int price = Integer.parseInt(price_txt .getText()); //creating variable for the price & getting values through getter methods
        
        p.setPno(pno);      //setting values through setter methods     
        p.setBrand(brand);  //setting values through setter methods
        p.setCategory(category);    //setting values through setter methods
        p.setPrice(price);  //setting values through setter methods
        p.setPname(search); //setting values through setter methods
        PhoneAcsImp acs = new PhoneAcsImp();
        acs.update(p);      //using the update method of PhoneAscImp class
        Load();     //calling load method 
        pno_txt.setText("");        //setting values through setter methods
        pname_txt.setText("");      //setting values through setter methods
        brand_txt.setText("");      //setting values through setter methods
        category_txt.setText("");   //setting values through setter methods
        price_txt.setText("");      //setting values through setter methods
        pname_txt.requestFocus();   //setting values through setter methods
       
       
        
    }//GEN-LAST:event_update_btnActionPerformed
  
    
    String search; //creating variable for searching
    
    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        
        Phone st = new Phone(); //creating new object for the Phone class
        st.setPname(search);  //setting values through setter methods
        
        PhoneAcsImp acs = new PhoneAcsImp(); //creating an object for PhoneAcsImp class
        acs.delete(st);         //using the delete method of PhoneAscImp class
        Load();     //calling load method 
        pno_txt.setText("");
        pname_txt.setText("");
        brand_txt.setText("");
        price_txt.setText("");
        category_txt.setText("");
        pname_txt.requestFocus();

        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void manage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_btnActionPerformed
        // TODO add your handling code here:
        
        Login1 lg = new Login1();
        lg.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_manage_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        
           //message box to enter the phone name
        search = JOptionPane.showInputDialog("Enter Phone Name!");
            //crateing new object for PhonAcsImp class
        PhoneAcsImp acs = new PhoneAcsImp();
        Phone st  = acs.get1(search);   //calling the get1 method

        pno_txt.setText(String.valueOf(st.getPno()));   //setting values through setter methods
        pname_txt.setText(st.getPname());               //setting values through setter methods
        brand_txt.setText(st.getBrand());               //setting values through setter methods
        category_txt.setText(st.getCategory());         //setting values through setter methods 
        price_txt.setText(String.valueOf(st.getPrice()));//setting values through setter methods
    }//GEN-LAST:event_search_btnActionPerformed

    private void search_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn2ActionPerformed
        
        //message box to enter the phone name
        search = JOptionPane.showInputDialog("Enter Phone Brand!");
           //crateing new object for PhonAcsImp class
        PhoneAcsImp acs = new PhoneAcsImp();    //calling the get1 method
        Phone st  = acs.get2(search);       //calling the get3 method

        pno_txt.setText(String.valueOf(st.getPno()));       //setting values through setter methods
        pname_txt.setText(st.getPname());                   //setting values through setter methods
        brand_txt.setText(st.getBrand());                   //setting values through setter methods
        category_txt.setText(st.getCategory());             //setting values through setter methods
        price_txt.setText(String.valueOf(st.getPrice()));   //setting values through setter methods
    }//GEN-LAST:event_search_btn2ActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField brand_txt;
    private javax.swing.JTextField category_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton manage_btn;
    private javax.swing.JTextField pname_txt;
    private javax.swing.JTextField pno_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton search_btn2;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
